version: "3.3"

services:
  db:
    image: postgres:latest
    hostname: virtualstore_db
    container_name: db
    environment:
      - POSTGRES_PASSWORD=vt123
      - POSTGRES_USER=virtualstore
      - POSTGRES_DB=virtualstore
    ports:
      - "5400:5400"
    expose:
      - "5400"
    volumes:
      - /home/morais/workspace/volume/postgresql:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    # -c max_connections=1000 -c shared_buffers=200MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off  -c log_min_messages=panic -c checkpoint_timeout=600 -c max_wal_size=4096 
    command: 'postgres -c config_file=/etc/postgresql/postgresql.conf'  
  

